"""empty message

Revision ID: f66ba27a51f6
Revises: 
Create Date: 2019-03-29 16:18:29.741053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66ba27a51f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=25), nullable=False),
    sa.Column('lastname', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.Column('director', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('announcements',
    sa.Column('annoucement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=5000), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['member.email'], ),
    sa.PrimaryKeyConstraint('annoucement_id')
    )
    op.create_table('progress_graph',
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('dprogress_graph', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['member.email'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress_graph')
    op.drop_table('announcements')
    op.drop_table('member')
    # ### end Alembic commands ###
